image: maven:3.6.3-openjdk-17

pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test Albummanager Application
            caches:
              - maven
            script:
              - mvn -B verify --file pom.xml
            after-script:
              - pipe: atlassian/checkstyle-report:0.2.0
        - step:
            name: Security Scan
            script:
              # Run a security scan for sensitive data.
              # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
              - pipe: atlassian/git-secrets-scan:0.4.3

definitions:
  services:
    mongo:
      image: mongo