image: docker/compose

pipelines:
  default:
#      - step:
#          name: Creating the Docker Images
#          script:
#            - docker version
#            - mvn package
#            - docker image ls
#          services:
 #           - docker
#            - mongo
      - step:
          name: Build and Test Albummanager Application
          caches:
            - maven
          script:
            - ci/dependencies.sh
            - docker-compose up
            - export TESTCONTAINERS_RYUK_DISABLED=true
            - mvn -B -X install --file pom.xml
          after-script:
            - pipe: atlassian/checkstyle-report:0.2.0
          services:
            - mongo
            - docker
            - redis


definitions:
  services:
    mongo:
      image: mongo:4.0.10
    redis:
      image: redis:3.0-alpine

