image: maven:3.6.3-openjdk-17

pipelines:
  default:
      - step:
          name: Creating the Docker Images
          script:
            - docker version
            - mvn spring-boot:build-image
            - docker image ls
          services:
            - docker
      - step:
          name: Build and Test Albummanager Application
          caches:
            - maven
          script:
            - export TESTCONTAINERS_RYUK_DISABLED=true
            - mvn -B install --file pom.xml
          after-script:
            - pipe: atlassian/checkstyle-report:0.2.0
          services:
            - mongo
            - docker


definitions:
  services:
    mongo:
      image: mongo:4.0.10

