version: "2.4"

services:
  albummanager:
    image: albummanager:0.0.1-SNAPSHOT
    ports:
      - "8080"
  albumrating-service:
    image: albumrating-service:0.0.1-SNAPSHOT
    ports:
      - "8081"
  albumwishlist-service:
    image: albumwishlist-service:0.0.1-SNAPSHOT
    ports:
      - "8082"
  redis:
    image: redis:3.0-alpine
    ports:
      - "6379"
  mongodb:
    image: mongo:4.0.10
    ports:
      - "27017"
